### ISSUE TITLE
Potential XSS security issue

### ISSUE THREAD

**Issue by vanyamil** [malbert911/HandRaiser#1]
Check this out : https://github.com/malbert911/HandRaiser/blob/9d4573a025df529f3b848a59d71acbd318b4b123/public/handraiser.js#L91

You are sending the data entered in room ID field directly into HTML. This could open you up for XSS (cross-site scripting) attacks. Even if it is blocked on the UI side by making the input field a number, that's not great protection.

Solution: test that the data is just a number and nothing else before appending it. `typeof` statement or `isFinite` function should fix it.

**Comment by malbert911** [comment]
In this context is myRoom is given by the server, which is sent on line 253 from their own request to join

https://github.com/malbert911/HandRaiser/blob/c7978c8bbdba34e60d47163166c50ad75122eac4/app.js#L253

Thank you for pointing this out. We had a check to prevent a XXS for the username with a .replace for special characters on line 242 but didn't do any checking for the room.
This has been updated in commit c7978c8bbdba34e60d47163166c50ad75122eac4

https://github.com/malbert911/HandRaiser/blob/c7978c8bbdba34e60d47163166c50ad75122eac4/app.js#L245

**Comment by vanyamil** [comment]
Great stuff, thanks!
